export const LABS_LIST_REQUEST = 'LABS_LIST_REQUEST'
export const LABS_LIST_SUCCESS = 'LABS_LIST_SUCCESS'
export const LABS_LIST_FAIL = 'LABS_LIST_FAIL'

export const LAB_SESSION_DETAILS_REQUEST = 'LAB_SESSION_DETAILS_REQUEST'
export const LAB_SESSION_DETAILS_SUCCESS = 'LAB_SESSION_DETAILS_SUCCESS'
export const LAB_SESSION_DETAILS_FAIL = 'LAB_SESSION_DETAILS_FAIL'
export const LAB_SESSION_DETAILS_RESET = 'LAB_SESSION_DETAILS_RESET'


